title: "Leyla Isazadeh Blog"
description: "A Personal technical notes and learning blog."
remote_theme: "just-the-docs/just-the-docs"

url: "https://lsazadeh.github.io"

aux_links:
  "My GitHub":
    - "//github.com/lsazadeh"

search_enabled: true

plugins:
  - jekyll-remote-theme


