title: "Leyla Isazadeh Blog"
description: "A Personal technical notes and learning blog."
remote_theme: "just-the-docs/just-the-docs"

url: "https://lsazadeh.github.io"

aux_links:
  "My GitHub":
    - "//github.com/lsazadeh"

search_enabled: true

plugins:
  - jekyll-remote-theme

# تنظیم منو
menu:
  C#:
    - title: "Fundamentals"
      url: "docs/csharp/fundamentals/index.md"
      has_children: true
    - title: "Object Oriented"
      url: "docs/csharp/object_oriented/index.md"
      has_children: true

# تنظیمات منو و صفحات دیگر
nav_order: 0
