title: leyla Isazadeh Blog
description: A Personal technical notes and learning blog.
remote_theme: just-the-docs/just-the-docs

url: https://Isazadeh.github.io

aux_links:
  My gitHub: https://github.com/Esazade

search_enabled: true